"""Generate notification_config.js from CI environment variables (GitHub Secrets).
Called by .github/workflows/deploy.yml during GitHub Pages deployment."""

import os


def s(key):
    """Read env var and escape single quotes to prevent JS string injection."""
    return os.environ.get(key, '').replace("'", "\\'")


config = f"""/* Auto-generated by CI — do not commit real credentials.
   See notification_config.example.js for local development instructions. */
globalThis.MT_SUPABASE_URL = '{s("SUPABASE_URL")}';
globalThis.MT_SUPABASE_ANON_KEY = '{s("SUPABASE_ANON_KEY")}';
globalThis.MT_FCM_VAPID_KEY = '{s("FCM_VAPID_KEY")}';
globalThis.MT_FIREBASE_CONFIG = {{
  apiKey: '{s("FIREBASE_API_KEY")}',
  authDomain: '{s("FIREBASE_AUTH_DOMAIN")}',
  projectId: '{s("FIREBASE_PROJECT_ID")}',
  storageBucket: '{s("FIREBASE_STORAGE_BUCKET")}',
  messagingSenderId: '{s("FIREBASE_MESSAGING_SENDER_ID")}',
  appId: '{s("FIREBASE_APP_ID")}',
}};
"""

output_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'notification_config.js')
with open(output_path, 'w') as f:
    f.write(config)

print(f'Generated {output_path}')
