const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')

test('user vault migration enables owner-only RLS policies', () => {
  const migrationPath = path.join(root, 'supabase/migrations/202606040001_secure_user_vaults.sql')
  const sql = fs.readFileSync(migrationPath, 'utf8')

  assert.match(sql, /create table if not exists public\.mt_user_vaults/i)
  assert.match(sql, /user_id uuid not null references auth\.users\(id\)/i)
  assert.match(sql, /alter table public\.mt_user_vaults enable row level security/i)
  assert.match(sql, /to authenticated\s+using \(\(select auth\.uid\(\)\) = user_id\)/i)
  assert.match(sql, /to authenticated\s+with check \(\(select auth\.uid\(\)\) = user_id\)/i)
  assert.doesNotMatch(sql, /\btransactions\b|\bwallets\b|\bamount\b|\bmerchant\b/i)
})

test('auth sync module enforces google-only sessions and does not store plaintext vault data', () => {
  const source = fs.readFileSync(path.join(root, 'auth_sync.js'), 'utf8')

  assert.match(source, /provider:\s*'google'/)
  assert.match(source, /code_challenge_method', 'S256'/)
  assert.match(source, /grant_type=pkce/)
  assert.match(source, /auth_code/)
  assert.match(source, /isGoogleSession/)
  assert.match(source, /mt_user_vaults/)
  assert.match(source, /ciphertext/)
  assert.match(source, /state\.locked = row \? true : !state\.dataKey/)
  assert.match(source, /function needsVaultUnlock\(\)/)
  assert.match(source, /debugSnapshot/)
  assert.match(source, /generateRecoveryKey/)
  assert.match(source, /ensureFirstRunBackup/)
  assert.match(source, /showRecoveryKeySheet/)
  assert.match(source, /คัดลอกรหัส/)
  assert.match(source, /เก็บรหัสนี้ไว้เพื่อกู้ข้อมูล/)
  assert.doesNotMatch(source, /Create cloud vault|Unlock cloud vault|ตั้ง cloud sync passphrase|passphrase/i)
  assert.doesNotMatch(source, /\.from\('mt_user_vaults'\)[\s\S]{0,500}(transactions|wallets|amount|merchant)/i)
})

test('auth sync gates app data before sign in and moves account controls into the more-page account menu', () => {
  const source = fs.readFileSync(path.join(root, 'auth_sync.js'), 'utf8')
  const appSource = fs.readFileSync(path.join(root, 'app_v2.js'), 'utf8')
  const css = fs.readFileSync(path.join(root, 'style_v2.css'), 'utf8')

  assert.match(source, /function renderAuthGate\(\)/)
  assert.match(source, /mt-auth-gated/)
  assert.match(source, /gate\.id = 'mt-auth-gate'/)
  assert.match(source, /Sign in with Google/)
  assert.match(source, /function accountMenuHtml\(\)/)
  assert.match(source, /function closeAccountMenu\(\)/)
  assert.match(source, /บัญชีและการกู้ข้อมูล/)
  assert.match(source, /data-mt-auth-action="toggle-account-menu"/)
  assert.match(source, /data-mt-auth-action="sync"/)
  assert.match(source, /showSavedRecoveryKeySheet/)
  assert.match(appSource, /MTAuthSync\?\.accountMenuHtml\?\.\(\)/)
  assert.doesNotMatch(appSource, /MTAuthSync\?\.settingsHtml\?\.\(\)/)
  assert.match(css, /\.more-title-row/)
  assert.match(css, /\.mt-account-menu-popover/)
  assert.match(css, /\.mt-auth-gated #app/)
  assert.match(css, /#mt-auth-gate/)
  assert.doesNotMatch(source, /id = 'mt-auth-sync'|id="mt-auth-sync"|className = 'mt-auth-sync'/)
})

test('sign out clears local account data before returning to auth gate', () => {
  const source = fs.readFileSync(path.join(root, 'auth_sync.js'), 'utf8')

  assert.match(source, /function confirmSignOut\(\)/)
  assert.match(source, /async function signOut\(\{ clearLocalData = true \} = \{\}\)/)
  assert.match(source, /clearTimeout\(state\.debounceTimer\)/)
  assert.match(source, /localStorage\.removeItem\(DEVICE_RECOVERY_KEY\)/)
  assert.match(source, /localStorage\.removeItem\(PKCE_VERIFIER_KEY\)/)
  assert.match(source, /root\.Storage\?\.reset\?\.\(\)/)
  assert.match(source, /document\.documentElement\.classList\.add\('mt-auth-gated'\)/)
  assert.match(source, /location\.reload\(\)/)
  assert.match(source, /data-mt-auth-action="confirm-sign-out"/)
})

test('auth restore waits for app storage bridge before creating or restoring vault data', () => {
  const source = fs.readFileSync(path.join(root, 'auth_sync.js'), 'utf8')

  assert.match(source, /function storageBridgeReady\(\)/)
  assert.match(source, /async function waitForStorageBridge/)
  assert.match(source, /await waitForStorageBridge\(\)/)
  assert.match(source, /root\.App\?\._cloudBuildPayload/)
  assert.match(source, /root\.App\?\._cloudApplyPayload/)
})
