const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.join(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

test('notification rule replacement is a service-role transactional RPC', () => {
  const migration = read('supabase/migrations/202610060002_notification_rule_replace_rpc.sql').toLowerCase()
  const sync = read('supabase/functions/sync-notification-rules/index.ts')
  assert.match(migration, /security\s+definer/)
  assert.match(migration, /set\s+search_path\s*=\s*public,\s*pg_temp/)
  assert.match(migration, /delete\s+from\s+public\.mt_notification_rules/)
  assert.match(migration, /insert\s+into\s+public\.mt_notification_rules/)
  assert.match(migration, /grant\s+execute[\s\S]*service_role/)
  assert.match(sync, /replaceNotificationRules/)
  assert.doesNotMatch(sync, /from\('mt_notification_rules'\)[\s\S]*\.delete\(/)
  assert.doesNotMatch(sync, /from\('mt_notification_rules'\)[\s\S]*\.insert\(/)
})

test('daily delivery claims and finishes through a lease-token-fenced path', () => {
  const migration = read('supabase/migrations/202610060003_daily_notification_delivery_claim.sql').toLowerCase()
  const daily = read('supabase/functions/send-daily-expense-reminders/index.ts')
  assert.match(migration, /create\s+or\s+replace\s+function\s+public\.mt_claim_daily_notification/)
  assert.match(migration, /lease_until\s*</)
  assert.match(migration, /grant\s+execute[\s\S]*service_role/)
  assert.match(daily, /deliverClaimedNotification/)
  assert.match(daily, /claimDailyNotification/)
  assert.match(daily, /\.eq\('lease_token', token\)/)
})

test('registration defaults preserve existing preferences and check persistence errors', () => {
  const helper = read('supabase/functions/_shared/notification_registration.ts')
  assert.match(helper, /upsert\(/)
  assert.match(helper, /ignoreDuplicates:\s*true/)
  assert.match(helper, /if \(error\) throw/)
})

test('deletion OTP uses CSPRNG, throttled RPC issuance, and atomic consumption', () => {
  const migration = read('supabase/migrations/202610060004_delete_otp_hardening.sql').toLowerCase()
  const send = read('supabase/functions/send-delete-otp/index.ts')
  const deleteAccount = read('supabase/functions/delete-account/index.ts')
  const otp = read('supabase/functions/_shared/delete_otp.ts')
  for (const column of ['attempt_count', 'requested_at', 'locked_until']) assert.match(migration, new RegExp(`add column if not exists ${column}`))
  assert.match(migration, /for\s+update/)
  assert.match(migration, /interval\s+'1 minute'/)
  assert.match(migration, /next_attempts\s+>=\s+5/)
  assert.match(migration, /interval\s+'15 minutes'/)
  assert.match(otp, /crypto\.getRandomValues/)
  assert.match(send, /issueDeleteOtp/)
  assert.doesNotMatch(send, /Math\.random/)
  assert.match(deleteAccount, /consumeDeleteOtp/)
  assert.doesNotMatch(deleteAccount, /from\('mt_delete_otps'\)/)
})
